### ISSUE TITLE
Pass Js-data create options to rethink

### ISSUE THREAD

**Issue by JesusisFreedom** [js-data/js-data-rethinkdb#21]
On https://github.com/js-data/js-data-rethinkdb/blob/master/src/index.js#L241 it appears that the opts are being left out from the actual call to insert.

In the case where I want to use {conflict: "replace"} or any more advanced rethink db options the options should be passed to the insert call.

**Comment by zparnold** [comment]
So we need to modify their ORM or is this working? Sorry I'm pretending like I know what Im talking about. Also, I want to be more involved in this...so get used to explaining things to me please! :)

**Comment by jmdobry** [comment]
Implemented in 3.x alpha

**Comment by jmdobry** [comment]
Candidate for porting back to 2.x
