### ISSUE TITLE
Cannot update any records: Inserted value must be an OBJECT (got ARRAY)

### ISSUE THREAD

**Issue by mikew** [js-data/js-data-rethinkdb#23]
I'm trying to update an existing record, not even doing anything complicated. Just calling `Model.update(id, newValues)` fails with `Inserted value must be an OBJECT (got ARRAY)`. Even when trying to just use the data I got from JSData in the first place.

```js
Survey
    .findAll({
      userId: req.user.id,
      id: req.params.id,
    })
    .then(x => {
      if (x.length === 0) {
        throw new Error(`No survey with id ${req.params.id}`)
      }

      const survey = x[0]
      // This logs out false, because the data is not an array
      console.log(Array.isArray(survey))
      // Yet this complains about the data being an array
      return Survey.update(survey.id, survey)
    })
```

Using:

```
- js-data@2.9.0
- js-data-rethinkdb@2.2.0
- rethinkdbdash@2.2.18
```

**Comment by internalfx** [comment]
```javascript
.then(x => {

      console.log(x) // What does this show?

      if (x.length === 0) {
        throw new Error(`No survey with id ${req.params.id}`)
      }
```

What does `x` look like?

**Comment by mikew** [comment]
`x` is an array resolved from `Model.findAll`. But we basically forget about it after checking to see if it's empty or not.

**Comment by mikew** [comment]
This code fails the same way, no arrays anywhere:

```js
Survey
    .find(req.params.id)
    .then(survey => {
      return survey.DSUpdate(survey)
    })
```

**Comment by internalfx** [comment]
What if you....

```js
Survey
    .find(req.params.id)
    .then(survey => {
      return survey.DSUpdate({test: true})
    })
```

**Comment by mikew** [comment]
Then it fails due to validations ... But that did lead me to my issue! When I wrote my `beforeUpdate` hook and saw ...

> The hooks' second argument is an object or an array of objects, depending on if the operation was triggered on a single item or a collection of items.

... in the JSData docs, I wrote it like so:

```javascript
// Handle updatedAt timestamps
function beforeUpdate (resource, attrs, done) {
  if (!Array.isArray(attrs)) {
    attrs = [attrs]
  }
  attrs.forEach(x => x.updatedAt = new Date())

  done(null, attrs)
}
```

Which seems to be the wrong way of handling an array of attrs.

**Comment by jmdobry** [comment]
You can't pass an array into `update` in v2. However, v3 adds support for `updateMany`, which takes an array.

`update` can only update a single document at a time. It updates the document specified by the `id` argument passed to `update`

**Comment by internalfx** [comment]
@mikew good to close?

**Comment by mikew** [comment]
@jmdobry Right, so how would one properly handle an array of attrs in a `beforeUpdate` hook? Since the docs do say it can happen.

@internalfx Yes good to close.

**Comment by jmdobry** [comment]
`beforeUpdate` should never receive an array, because you shouldn't pass an array to `update`. In v2, array handling would need to happen outside of js-data with something like `Promise.all(array.map(...))`

**Comment by mikew** [comment]
Then why do the docs state it can? Or have they just not been updated.

> The hooks' second argument is an object or an array of objects, depending on if the operation was triggered on a single item **or a collection of items**.
>
> - `beforeUpdate(resource, attrs|arrayOfAttrs[, cb])`

**Comment by jmdobry** [comment]
The docs are wrong. Can you put a link here to where it says that?

**Comment by mikew** [comment]
http://www.js-data.io/docs/model-lifecycle#section-ds-save-ds-update-ds-updateall

**Comment by jmdobry** [comment]
Ah, I forgot about `updateAll`. So:

```js
function beforeUpdate (resource, attrs, done) {
  if (Array.isArray(attrs)) {
    attrs.forEach(x => x.updatedAt = new Date())
  } else {
    attrs.updatedAt = new Date()
  }
  done(null, attrs)
}
```

**Comment by mikew** [comment]
Perfect, I'd already changed it to that after opening this issue. Thanks for the help you two!

**Comment by jmdobry** [comment]
In v3 the hook is split into `beforeUpdate`, `beforeUpdateAll`, and `beforeUpdateMany`.
